### PR TITLE
Fixed header structure and adapted reference style

### PR DESCRIPTION
**Pull request by M-earnest**

### CODE REVIEW

**Comment by PeerHerholz** [comment]
[EEG](https://trello.com/c/zggy5iha/2-eeg)

**Comment by PeerHerholz** [comment]
Thx for the updates and fixes! Could you maybe resolve the `merge conflict` before we start the review? Merci!

**Comment by PeerHerholz** [comment]
Thx for resolving the `merge conflict`! @felixkoerber and I will now conduct the review and will update asap.

**Review by PeerHerholz — CHANGES_REQUESTED** [review]
Thx for the updates, I think the `header structure` and `reference style` should be ok now. Could you please remove the `checkpoint`s again (you can simply add those to the `.gitignore` to avoid that going forward) and change the `kernel` you used within the `notebooks`? Re the latter: it currently doesn't point to/utilizes `neuro_ai` but your default `python kernel`.

**Comment by M-earnest** [comment]
Thx for the feedback. Kernel should be good to  go now, checkpoints removed.

**Comment by M-earnest** [comment]
> Thx for the updates, I think the `header structure` and `reference style` should be ok now. Could you please remove the `checkpoint`s again (you can simply add those to the `.gitignore` to avoid that going forward) and change the `kernel` you used within the `notebooks`? Re the latter: it currently doesn't point to/utilizes `neuro_ai` but your default `python kernel`.

Thx for the feedback. Kernel should be good to  go now, checkpoints removed.

**Review by felixkoerber — APPROVED** [review]

**Review by PeerHerholz — APPROVED** [review]
LGTM, thx!

**Pull request merged**
