### PR TITLE
add EEG chapters

### PR DESCRIPTION
**Pull request by M-earnest**
- added Notebooks on 
  - EEG Introduction
  - MNE python introduction
  - Preprocessing with MNE
  - ERP/EVP analysis with MNE
  - MNE workflow example

- added PNG for EEG intro and workflow tutorial setup

### CODE REVIEW

**Review by PeerHerholz — COMMENTED** [review]
thx for this! I only have a few comments/questions: 

- it seems that the `_toc.yml` wasn't updated to include the new notebooks
- I was wondering if parts of the `mne` notebooks could be combined, e.g. `preprocessing`& `workflow_preparation`

**Comment by M-earnest** [comment]
Good catch!

- Should I add the updated _toc.yml in a new pull request?
- The preprocessing and workflow preparation notebooks can’t really be combined, as the latter is merely an instruction for the download of data used for the workflow tutorial notebook instead of an mne content chapter. Alternatively the workflow preparation notebook could be moved into a static folder and referenced at the beginning of the workflow tutorial notebook?

**Comment by PeerHerholz** [comment]
> * Should I add the updated _toc.yml in a new pull request?

You can just update, `commit` and `push` to your `branch` so that we include here.

> * The preprocessing and workflow preparation notebooks can’t really be combined, as the latter is merely an instruction for the download of data used for the workflow tutorial notebook instead of an mne content chapter. Alternatively the workflow preparation notebook could be moved into a static folder and referenced at the beginning of the workflow tutorial notebook?

Hm, kk. Could we maybe still try it out? I would like to avoid having several `notebooks`/`sections` that more or less directly depend on one another as this might make it harder to navigate/easier to miss something. Maybe a narrative like "Before we start exploring workflows, we will download and prepare corresponding data." could work?

**Comment by M-earnest** [comment]
> > * Should I add the updated _toc.yml in a new pull request?
> 
> You can just update, `commit` and `push` to your `branch` so that we include here.

Will do!



>
> Hm, kk. Could we maybe still try it out? I would like to avoid having several `notebooks`/`sections` that more or less directly depend on one another as this might make it harder to navigate/easier to miss something. Maybe a narrative like "Before we start exploring workflows, we will download and prepare corresponding data." could work?

Understood. Will rework the preparation notebook as an intro to the workflow tutorial, only concern might be that the tutorial may get somewhat less focused.

**Comment by PeerHerholz** [comment]
Thx for the changes. It seems we have a merge conflict re the `_toc.yml` now which would need to be resolved. Furthermore, could you please update the `_toc.yml` so that it follows the remaining sections more closely? Specifically, the `mne` `notebooks` should be `sections` of the `eeg introduction` `notebook`.

**Comment by PeerHerholz** [comment]
Coolio, merci. I think we're almost there: could you please remove all the `...checkpoint.ipynb` files?

**Comment by M-earnest** [comment]
Awesome. Will do

**Comment by PeerHerholz** [comment]
LGTM, thx!

**Pull request merged**
